### ISSUE TITLE
Multilayer panels. (Panels inside other panel)

### ISSUE THREAD

**Issue by eliogrin** [Invictum/invictum-test#21]
**Example:** I have search result page with big count of filters. I create sidebar panel, which one include all possible filters. Each filter is separate panel. 
So I will get access to panel something like that:
`getPanel(SidebarPanel.class).getPanel(SomeFilter.class);`

Is it possible to implement such functionality?

**Comment by Invictum** [comment]
I assume it is possible. But double getPanel looks really ugly. I think it will be better do not use such small palels dividing. In your example use only one panel SearchPanel that will be include all filters logic. What do you think?

**Comment by eliogrin** [comment]
@Invictum may be this example is not show what I want to say, I will try another one:
**Example**: I am on shopping cart page with different numbers of items in cart. Each item should have methods:
- getTitle()
- getDescription()
- getColor()
- getPrice()
- updateCount()
- removeItem()
- etc.
  In this case I would like to create panel for all items in shopping cart, and separate for each item in cart. As for me, this approach can be pretty useful.

**Comment by Invictum** [comment]
In your example I'd prefer to create shopping cart items panel. Because it is much easier to deal with remove or extract data in dto for assertion (list of shopping cart items dto) in scope of single panel.
Example 1: you need to remove some item. How to specify remove criteria? In most cases you need to foreach items and try to check some unique attribite (i. g. title). This is only way how to remove item and you should do the same for multiple panels approach. so what an advantage of multi panels in this case?
Example 2: you need to assert all cart items data. for this you need two lists of dto. For multi panel approach you need to foreach panels and invoke get something methods. The same activity should be performed for complex panel approach (get items elements and collect data for each of them) So where is an advantage of multi panel approach?

But it is still possible to implement it, but I propose following limitations:
- make getPanel for panels protected. This will help is avoid ugly page.getPanel().getPanel() chains.
- getPanels method should be also implemented on page level.
  What do you thing about it?

**Comment by Invictum** [comment]
@eliogrin 
How to handle locator root in case of initing panel inside panel?

**Example**
We have a panel A with some defined base. Let's assume we try to init panel B inside of A. How to determinate root of B? I think there are two options:
- **easy way** - init panel in scope of parent page based on panel B base.
- **hard way** - init panel in scope of panel A (perform panel B element search in scope of A panel).

Maybe you have some ideas about it?

**Comment by Invictum** [comment]
Implemented. Will be available in version 1.0
